### ISSUE TITLE
bml deprecated error

### ISSUE THREAD

**Issue by waffel** [Buzztrax/build-tools#6]
I get following error with jhbuild:

*** Building bml *** [3/8]
make -j 3
Makefile:1980: warning: overriding recipe for target 'all'
Makefile:711: warning: ignoring old recipe for target 'all'
*
* This module has been discontinued and merged into buzztrax!
*
Makefile:1980: recipe for target 'all' failed
make: *** [all] Error 1
*** Error during phase build of bml: ########## Error running make -j 3 *** [3/8]

Do we need to remove this module?

**Comment by ensonic** [comment]
Yes, I have not updated the jhbuild module. Now we only need to build buzztrax and buzzmachines. That makes the configure a lot simpler etc.
